# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b5ac910c759e4d470c8118084a108d0cee5963e225db1fe619d4fb5021d659b933639ce3e7761883ed19e05d67bed974e882449a95d9c89bd506e0df3241c1c

test:
  secret_key_base: ed9bd3428be3f858ab7de31c5816cdff145549da3e82970213a4b5ab772705f517b3f1b0fe45d1a011a8fdeee2d0990ed6410e57bd8e041762e1e9443dcafb83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
